### PR TITLE
#514 make requested changes

### LINKED ISSUE #514: OpenCL detection on OS/X doesn't seem to work
Hi @MichaelClerx 
Happy Easter! I was writing some tests for the new importer and suddenly realised that there are some import errors with some myokit modules, even in the master. I installed the package with `pip install -e .[docs,dev,pyqt]` and then ran the minimal tests `python run_tests.py --minimal`. A bunch of seemingly similar errors pop up:
```
======================================================================
ERROR: test_simulation_p (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_simulation_p
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/tests/test_simulation_p.py", line 17, in <module>
    from shared import DIR_DATA, CancellingReporter
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/tests/shared.py", line 33, in <module>
    OpenCL_FOUND = myokit.OpenCL.supported()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 206, in supported
    OpenCL._get_instance()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 90, in _get_instance
    OpenCL()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 65, in __init__
    mname, fname, args, libs, libd, incd)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 197, in _compile
    return load_module(name, d_modul)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 54, in load_module
    module = importlib.util.module_from_spec(spec)
ImportError: dlopen(/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so, 2): Symbol not found: _clGetDeviceIDs
  Referenced from: /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so
  Expected in: flat namespace
 in /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so
```

Have you had this problem before?

_Originally posted by @DavAug in https://github.com/MichaelClerx/myokit/issues/433#issuecomment-611998266_

### PR DESCRIPTION
**Pull request by DavAug**
Closes #514 

Sorry for the shitty branch name, but it seems to work with your suggested changes.

### CODE REVIEW

**Comment by DavAug** [comment]
Ok I know too little about this to easily debug the problem. But it seems that generally the changes work, bit only specific conifgurations of the simulator fail.

Btw. how do you install sundials on Travis for Mac? Just before Christmas the brew script got updated and since then my GitHub actions seem to be unable to install sundials properly, e.g. https://github.com/DavAug/erlotinib/runs/1577797747?check_suite_focus=true

**Comment by MichaelClerx** [comment]
Thanks @DavAug !

**Comment by MichaelClerx** [comment]
These two lines work for me:

https://github.com/MichaelClerx/myokit/blob/main/.travis.yml#L84-L85

**Comment by MichaelClerx** [comment]
@DavAug new osx installation script: https://github.com/MichaelClerx/myokit/blob/main/.github/workflows/install-osx-dependencies.sh

**Pull request merged**
