### PR TITLE
859 memory leak cvodessim

### LINKED ISSUE #859: Further memory leak (probably in C code)
Following the fix #855 I still experienced an explosion of memory usage in my inference algorithm which still seems to be related to `myokit.Simulation.run()`. In contrast to the protocol, I can, however, no longer see the growing memory in Python objects, i.e. using pympler as in #855 . But using the same example

```
import myokit

m, p, x = myokit.load('example')
s = myokit.Simulation(m, p)

for _ in range(100000):
    s.run(1000)
```

and the command line process profiler 

```[bash]
top
```

I can see that over time the memory usage grows / the available memory decreases linearly in time, i.e. proportional to the number of `myokit.Simulation.run()` calls. Here are two snapshots 2 minutes apart and we can see that the available memory reduces from 14672.1 to 14640.7 / that the memory usage of the python process increases from 0.3% of the total memory to 0.5% of the total memory.

```
top - 10:10:47 up 2 days,  3:43,  1 user,  load average: 0.28, 0.15, 0.24
Tasks: 244 total,   2 running, 242 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.5 us,  0.0 sy,  0.0 ni, 87.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15772.3 total,  12875.2 free,    688.6 used,   2208.4 buff/cache
MiB Swap:  32768.0 total,  32768.0 free,      0.0 used.  14672.1 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  15964 davtin    20   0  569132  46200  15344 R  99.7   0.3   0:17.14 python
```

```
top - 10:12:47 up 2 days,  3:45,  1 user,  load average: 0.91, 0.44, 0.34
Tasks: 244 total,   2 running, 242 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.5 us,  0.0 sy,  0.0 ni, 87.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15772.3 total,  12843.8 free,    720.0 used,   2208.5 buff/cache
MiB Swap:  32768.0 total,  32768.0 free,      0.0 used.  14640.7 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  15964 davtin    20   0  597124  74184  15344 R  99.7   0.5   2:17.18 python
```

For my (bigger) model this is enough to kill the processes after 12h because the computer runs out of memory. Do you have an idea how we might tackle this?

### PR DESCRIPTION
**Pull request by DavAug**
Closes #859

### CODE REVIEW

**Comment by DavAug** [comment]
I think that was it 🥳🥳 At least I cannot see the memory usage growing anymore when I run the example from #859 .

**Comment by MichaelClerx** [comment]
Great work @DavAug !

Can you confirm that this snippet shows a number going from >0 before the fix to 0 after?

```
#!/usr/bin/env python3
import resource
import myokit

m, p, _ = myokit.load('example')
s = myokit.Simulation(m, p)

s.run(10, log=myokit.LOG_NONE)

u1 = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
for i in range(100):
    s.run(1, log=myokit.LOG_NONE)
u2 = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

print(u2 - u1)
```

**Review by MichaelClerx — APPROVED** [review]

**Comment by DavAug** [comment]
> #!/usr/bin/env python3
> import resource
> import myokit
> 
> m, p, _ = myokit.load('example')
> s = myokit.Simulation(m, p)
> 
> s.run(10, log=myokit.LOG_NONE)
> 
> u1 = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
> for i in range(100):
>     s.run(1, log=myokit.LOG_NONE)
> u2 = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
> 
> print(u2 - u1)

So I am supposed to get something greater 0 without the fix? I seem to get 0 regardless

```
(venv) ➜  myokit git:(859-memory-leak-cvodessim) ✗ python todelete.py
WARNING:myokit:Using development version of Myokit (1.33.4.dev).
0
(venv) ➜  myokit git:(main) ✗ python todelete.py
WARNING:myokit:Using development version of Myokit (1.33.4.dev).
0
```

**Comment by DavAug** [comment]
Ah ok nvm I didn't realise we just merged the PR 😂. If I use an outdated branch I get a number greater 0
```
(venv) ➜  myokit git:(main) ✗ python todelete.py
WARNING:myokit:Using development version of Myokit (1.32.1.dev).
8192
```

**Comment by MichaelClerx** [comment]
Thanks @DavAug ! Really nice work :-D

**Comment by DavAug** [comment]
> Thanks @DavAug ! Really nice work :-D

Haha thanks, I'm just happy I was lucky enough to guess correctly 😂

**Comment by MichaelClerx** [comment]
I'm very happy that you found it, and that a second person now has touched the C code.
I'm a bit unhappy that I made this mistake, and then didn't find it when I checked a few weeks ago.
But happy on the whole :D 

To address some of your earlier comments:

Things like integers, floats, and even fixed-size arrays in C won't cause memory leaks. But if you create a dynamically-sized array, e.g. one with a size that isn't know at compile time, then you need to use `free()` to release the memory again yourself. (The _Create(..) _Destroy(..) things you see in sim_clean and sim_init are just functions that do all the free-ing for a particular library).

So what I was doing here was allocating space for y_last, and then not telling the OS to release it again

**Pull request merged**
